### ISSUE TITLE
[Feature Request ?] Time to Max NGU

### ISSUE THREAD

**Issue by thertemis** [jshepler/jshepler.ngu.mods#13]
Hi,
It would be nice to see, in NGU when Target is 0, the number of levels and the estimate time to reach the max Value. And/Or a way to set  the Target to the maximum level. The wiki only indicates the max value of NGU skills and not the max level to get to it.
Thank you.

**Comment by jshepler** [comment]
The max level is 1e+9 (1 billion) and the wiki does say that:
![image](https://github.com/user-attachments/assets/97af25da-0edb-47d5-a1a8-515bcfd5fe22)

Don't put that in for a target unless you're close as it may stall the game trying to iterate over that many levels.

Because of that, I will not be showing time to reach hardcap when target is 0. Sorry.
