### ISSUE TITLE
I always get the same Quest Item objectives where adventure zone im currently in

### ISSUE THREAD

**Issue by Ferosauce** [jshepler/jshepler.ngu.mods#5]
For example. When I finish or skip a PPPL major quest, the next quest will still be in PPPL adventure zone.

https://github.com/user-attachments/assets/686c1f8e-26f3-494f-8b53-a8806f96f918

**Comment by Ferosauce** [comment]
I just read that this is a feature, is there a option to make it random?

**Comment by jshepler** [comment]
The README says, "when starting a manual quest, if **current zone has unlocked quest item**, that item is assigned as the quest (instead of random quest item)", i.e. if current zone does not have an unlocked quest item, you will get a random one - so go to a zone that doesn't drop a quest item, like ITOPOD, if you really want a random one.

The point of the mod is so that you don't need to continually skip/start random quests to get to the one you want, presumably one that hasn't been leveled to 100 yet. This way, you get to choose the one you want by going to the zone that drops it. It doesn't do anything you can't do for yourself, just saves some time.

It also allows the auto manual major questing to work without adding an auto goto quest zone function.

**Comment by jshepler** [comment]
In case you hadn't noticed it, release 1.13 added the option to always get random quests.
